#数据源配置
spring:
  datasource:
    url: jdbc:mysql://118.190.208.205:3306/chat?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    data-username: root
    password: cherish
    tomcat:
      initial-size: 5
      max-active: 20

#mybatis配置
  mybatis.config-location=classpath:mybatis-config.xml
  mybatis.mapper-locations=classpath:com/cherish/chat/mappers/*.xml


#redis配置
  spring.redis.database=0
  #服务器地址
  spring.redis.host=127.0.0.1
  #服务器端口号
  spring.redis.port=6379
  #服务器连接密码
  spring.redis.password=
  #最大连接数
  spring.redis.pool.max-active=1000
  #连接池最大阻塞等待时间
  spring.redis.pool.max-wait=-1
  #连接池最大空闲连接
  spring.redis.pool.max-idle=8
  #连接池最小空闲连接
  spring.redis.pool.min-idle=0
  #连接超时时间
  spring.redis.timeout.0


  #文件上传配置
  spring.http.multipart.enabled=true
  #上传中转文件位置
  spring.http.multipart.location=E:/upload
  #最大上传文件大小
  spring.http.multipart.max-file-size=5MB

  server.port=9999
  server.servlet.context-path=/MyChat
  server.jsp-servlet.init-parameters.development=true

  #试图解析器
  spring.mvc.view.prefix=/
  spring.mvc.view.suffix=.jsp
